DROP TABLE crsp_mth_stock;
CREATE EXTERNAL TABLE crsp_mth_stock
(
  PERMNO string,
  date string,
  NAMEENDT string,
  SHRCD string,
  EXCHCD string,
  SICCD string,
  NCUSIP string,
  TICKER string,
  COMNAM string,
  SHRCLS string,
  TSYMBOL string,
  NAICS string,
  PRIMEXCH string,
  TRDSTAT string,
  SECSTAT string,
  PERMCO string,
  ISSUNO string,
  HEXCD string,
  HSICCD string,
  CUSIP string,
  DCLRDT string,
  DLAMT string,
  DLPDT string,
  DLSTCD string,
  NEXTDT string,
  PAYDT string,
  RCRDDT string,
  SHRFLG string,
  HSICMG string,
  HSICIG string,
  DISTCD string,
  DIVAMT string,
  FACPR string,
  FACSHR string,
  ACPERM string,
  ACCOMP string,
  SHRENDDT string,
  NWPERM string,
  DLRETX string,
  DLPRC string,
  DLRET string,
  TRTSCD string,
  NMSIND string,
  MMCNT string,
  NSDINX string,
  BIDLO string,
  ASKHI string,
  PRC string,
  VOL string,
  RET string,
  BID string,
  ASK string,
  SHROUT string,
  CFACPR string,
  CFACSHR string,
  ALTPRC string,
  SPREAD string,
  ALTPRCDT string,
  RETX string,
  vwretd string,
  vwretx string,
  ewretd string,
  ewretx string,
  sprtrn string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES
(
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/financial_data/crsp_mth_stock';

